### ISSUE TITLE
Can't see WS

### ISSUE THREAD

**Issue by charkster** [vijaymarupudi/sph0645-pico-troubleshooting#1]
Great program! ~~I can see WS being driven at 48kHz on GP4~~, but I can't see SCLK on GP3 (~~or any of the first 8 GP pins~~). I am using a 24MHz logic analyzer to look at the signals (using 24MHz sampling). Is the github version different from your local version?
When I was seeing all zeros for mic data I disconnected the mic wires and connected the logic analyzer directly to the Pico. I needed to add a `sleep_ms(5000);` right after `init();` in order to be able to capture the signals after inserting the Pico USB cable. No other changes. Tried on 2 different Pico boards... same result.

Separate from this issue, I was thinking of switching the uart port to USB serial and adding a menu for triggering the i2s data capture... it actually works pretty well, just no SCLK.

**Comment by vijaymarupudi** [comment]
This version is the version that worked for me. It is possible that your mic has a SELECT pin that tied HIGH? In that case, the NOPs in the PIO file should be swapped, as data is only captures when the WS and SELECT are the same.

In my case, using the Adafruit's SPH0645 breakout board, they are low.

If the WS is being driven, I see no reason why the SCLK is not driven. Can you check its voltage?

**Comment by charkster** [comment]
Thanks for the quick response. I attached my oscilloscope and am seeing the SCLK now, but it is on GP4.
I am using the Pico's GND reference on my probes, I don't know why they are so noisy. The wires are connected to the mic.
I set up the oscilloscope before I plugged in the Pico's usb cable. I was hoping to see WS on GP4 and SCLK on GP3 (CH1 of the oscilloscope is on GP3). CH2 of the oscilloscope is on GP2.

![pico_i2s_connected](https://user-images.githubusercontent.com/31560568/112740150-712de480-8f2f-11eb-9367-4f88d128c2ae.png)
![pico_i2s_connected_zoom](https://user-images.githubusercontent.com/31560568/112740152-755a0200-8f2f-11eb-87d1-003bee9007fd.png)

Here are captures when the Pico is not connected to the mic (channels and signal names are the same as before). The signals coming out of the Pico are noisy... it's not my scope. Looks like whether signals are connected to the mic or not, doesn't matter from a noise point of view.

![pico_i2s_not_connected](https://user-images.githubusercontent.com/31560568/112740296-9ec75d80-8f30-11eb-8f0e-2dad50547f46.png)

![pico_i2s_not_connected_zoom](https://user-images.githubusercontent.com/31560568/112740301-a25ae480-8f30-11eb-8355-a318742d71e0.png)

I was able to get my logic analyzer to capture the beginning of the i2s start (just like the oscilloscope did). The GP4 pin is driving the SCLK at 3MHz, and the toggles on the other channels are the noise from the Pico (it is high enough to show a false transition).

![Screenshot from 2021-03-27 19-30-13](https://user-images.githubusercontent.com/31560568/112740576-e818ac80-8f32-11eb-9ff3-d76209d00d71.png)

![Screenshot from 2021-03-27 19-27-17](https://user-images.githubusercontent.com/31560568/112740583-ebac3380-8f32-11eb-9599-a01d9e4ebd24.png)

Sorry about the bad name for this issue... it really is the WS that is missing. I will update the title.

**Comment by charkster** [comment]
Is the SCLK supposed to run by itself without the WS for a while before you capture data? WS does not look like it is toggling for the first 1ms.

I made sure that my select line is low (I also had it tied low). I am able to record audio from this mic on the RPi4b.
Should I be looking for the WS 100ms after SCLK starts?

**Comment by charkster** [comment]
I captured more time, but just see noise on GP2 and GP3. SCLK is running like a champ.

![Screenshot from 2021-03-27 19-44-04](https://user-images.githubusercontent.com/31560568/112740826-f9fb4f00-8f34-11eb-8a5d-11f9dd333abd.png)

![Screenshot from 2021-03-27 19-44-27](https://user-images.githubusercontent.com/31560568/112740833-ff589980-8f34-11eb-807a-b9bddf7e0f70.png)

**Comment by charkster** [comment]
I am assuming that when you define clock_pin_base in sph0645.pio, that WS would be the next signal (after the SCLK). 
Is bit_loop0 when WS is low and bit_loop1 when WS is high?

**Comment by charkster** [comment]
I am seeing WS on the next pin. My Pico pinout that I googled for had the wrong GP pin names. They are supposed to start at GP0 but the diagram that I found had them starting at GP1. Your pin numbers are correct, I was referencing the wrong pins.
Sorry for the long posts... I get very verbose when I am trying to solve a problem.

![Screenshot from 2021-03-27 20-14-03](https://user-images.githubusercontent.com/31560568/112741256-04b7e300-8f39-11eb-81bd-c2a763722218.png)

**Comment by vijaymarupudi** [comment]
Glad you were able to figure it out!

I'm curious, which logic analyzers are you using, and what's the software you're using the visualize it in the last image? I'm looking to get some, so would appreciate recommendations @charkster!

Sorry about the messy code, didn't have time to continue the project until another month or so, so no code cleanup happened.

**Comment by charkster** [comment]
This is the logic analyzer that I have, and it works great ($12):
https://www.amazon.com/HiLetgo-Analyzer-Ferrite-Channel-Arduino/dp/B077LSG5P2
The ferrite ring on the cable is a good thing as 24MHz * 8 channels is close to the max USB 2.0 reliable data rate (you don't want lots of EMI when you are making measurements). The reason it is so cheap is that it quickly streams the captured data over the cable and into the dram on the computer it is connected to. I use it on my RPi4. Sigrok pulseview is the software that I use and I use the version on the Raspberry Pi OS repo.
`sudo apt-get install pulseview sigrok-firmware-fx2lafw`
It works down to about 1.5V, which is good most times, but in the Pico's case I saw noise on the unused GP pins. I use the 10 pin cable that they provide, and I made my own 0->7 channel labels with sticky labels covered in clear tape.
It can get "stuck" sometimes, but just re-starting pulseview is easy to do. It can be configured to start capture on a rising/falling edge... just click the channel icon that you want to trigger on and it will show you a menu to select an option. Remember that if you select triggers on multiple channels, they all need to be true to start capturing (it is not an OR condition). The screwdrive/wrench symbol controls the amount of time before the trigger of data captured (as a percentage of the total samples captured). I always use 24MHz sampling as most of the signals I look at are fast. It works just like an oscilloscope except it shows 1s and 0s.

Thanks for putting this project on Github, it motivated me to buy the Pico. I already added a couple of changes to your code... (1) use USB uart, (2) wait for serial port connection and character press before capturing samples and (3) add a define for the sample rate and number of bits (I have another mic with a 16bit sample width). I need to figure out why there is a small burst of SCLKs and then a dead time at the beginning (as seen in the captures above). 

I also use a 3 pin 30V voltmeter powered by the RPI's 3.3V which I got on Amazon... as seen in the picture below. They are about $10 for a 5 pack and are so much more convenient than a multimeter.
https://www.amazon.com/bayite-Digital-Voltmeter-Display-Motorcycle/dp/B00YALUXH0

![IMG_20210328_180117_719](https://user-images.githubusercontent.com/31560568/112774906-fbd61880-8fef-11eb-9dfb-d6814011557a.jpg)

**Comment by vijaymarupudi** [comment]
I'm glad I got to help, it really is a neat board, especially the documentation.

I'm definitely going to get that analyzer, it's not even that expensive! It's possible that the noise in the GPIO pins that are not being used it use to their default state, where there is no pullup or pulldown resistor. But it might be EM interference too...

I'm not sure about the pulse of SCLK... That did not happen to me, the audio signal was usable pretty much immediately after starting the PIO. The PCM values started high and then centered around a small negative value, so that's odd.

Please upload your code to github too, when you find the time, I think the Pico might be a great audio platform. Although I have yet to test FFT performance for anything complicated.

Yes, the UART in this code was just temporary, I'll have to write a USB Audio
Driver to use it on a computer, or link it to a PWM based speaker or a DAC. USB serial is definitely a much faster alternative, I was using UART because I was debugging the Pico using SWD, which I highly recommend. However, it kinda stops the USB during the debug session. You can use an FT232H with openocd for SWD, and also for other things so it's a good swiss army knife to have.

One thing I was planning to do was use the DMA (you might have noticed the dead code) and to change the PIO to only record 16 bits, and then use nops for the rest. This should allow a decent amount in space in RAM to do other programming stuff in sequence with the audio, because currently, only a second can fit into RAM at once.

Appreciate you sharing your setup, I'm going to expand mine pretty soon and this was great timing.
