### ISSUE TITLE
Help for inmp441

### ISSUE THREAD

**Issue by croisez** [vijaymarupudi/sph0645-pico-troubleshooting#3]
Hi,
i saw your [post on the raspberry-pi forum](https://forums.raspberrypi.com/viewtopic.php?t=304368).
This is awesome, thank you for giving this to us.
You wrote in your Readme that for I2S mics other than SPH0645, we have to toggle clk 0's and 1's in the .pio file.
I have no experience with RPI-pico, so would you like to help me modifying your .pio file for my I2S microphone: INMP441

**Comment by vijaymarupudi** [comment]
Hi croisez,

The clock bit was the lowest side bit in the .pio file. I flipped the relevant part here, replace the part in this file (https://github.com/vijaymarupudi/sph0645-pico-troubleshooting/blob/master/sph0645.pio) with this.

```
bitloop1:           
    in pins, 1       side 0b01
    jmp x-- bitloop1  side 0b00
    in pins, 1       side 0b11
    set x, 30         side 0b10

bitloop0:
    nop       side 0b11
    jmp x-- bitloop0  side 0b10
    nop       side 0b01
public entry_point:
    set x, 30         side 0b00
```

**Comment by croisez** [comment]
thank you for your help
